import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, Check, Eye, File, FileText, Presentation, RefreshCw, Upload } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { ZhiyunImportDialog } from '@/components/product/ZhiyunImportDialog'
import { productApi } from '@/api/product'
import type { DatasetDetail, Resource } from '@/product-types'

const iconFor = (kind: Resource['kind']) => ['pptx', 'courseware'].includes(kind) ? Presentation : kind === 'transcript' ? FileText : File
const formatSize = (value = 0) => value < 1024 ? `${value} B` : value < 1024 * 1024 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`

export function DatasetDetailPage() {
  const { datasetId = '' } = useParams()
  const navigate = useNavigate()
  const input = useRef<HTMLInputElement>(null)
  const [detail, setDetail] = useState<DatasetDetail | null>(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [preview, setPreview] = useState<{ title: string; text: string } | null>(null)
  const [showImport, setShowImport] = useState(false)
  async function load() { try { setDetail(await productApi.dataset(datasetId)) } catch (err) { setError((err as Error).message) } }
  useEffect(() => { void productApi.dataset(datasetId).then(setDetail).catch((err) => setError((err as Error).message)) }, [datasetId])
  async function upload(files: FileList | null) { if (!files?.length) return; setBusy(true); setError(''); try { for (const file of Array.from(files)) await productApi.upload(datasetId, file); await load() } catch (err) { setError((err as Error).message) } finally { setBusy(false); if (input.current) input.current.value = '' } }
  async function showPreview(resource: Resource) { const revision = resource.current_revision; if (!revision) return; try { const data = await productApi.preview(revision.revision_id); setPreview({ title: resource.title, text: data.text }) } catch (err) { setError((err as Error).message) } }
  if (!detail) return <div className="p-10 text-sm text-[#718183]">{error || '正在读取资料集…'}</div>
  const ready = detail.resources.filter((item) => item.current_revision?.parse_status === 'ready').length
  return <div className="mx-auto max-w-[1180px] px-4 py-6 md:px-10 md:py-9"><Link to="/datasets" className="inline-flex items-center gap-2 text-sm text-[#718183] hover:text-[#147d86]"><ArrowLeft size={15} />返回资料库</Link><header className="mt-6 flex flex-col items-start justify-between gap-4 border-b border-[#dfe6e6] pb-6 lg:flex-row"><div><h1 className="text-[28px] font-semibold">{detail.dataset.name}</h1><p className="mt-2 text-sm text-[#718183]">{detail.dataset.description || '在这里长期保存所有课程资料；生成时再选择本次使用范围。'}</p></div><div className="flex gap-2"><input ref={input} type="file" multiple accept=".pptx,.pdf,.docx,.md,.markdown,.txt" className="hidden" onChange={(e) => void upload(e.target.files)} /><Button variant="outline" disabled={busy} onClick={() => input.current?.click()}><Upload size={15} />上传文件</Button><Button disabled={busy} onClick={() => setShowImport(true)} className="bg-[#147d86] text-white hover:bg-[#116a72]"><RefreshCw size={15} />导入智云课程</Button></div></header>
    <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3 sm:gap-4">{[[detail.resources.length,'全部资料'],[ready,'解析可用'],[detail.snapshots.length,'输入快照']].map(([value,label]) => <div key={label} className="rounded-lg border border-[#dfe6e6] bg-white p-4"><strong className="text-2xl">{value}</strong><p className="mt-1 text-xs text-[#718183]">{label}</p></div>)}</div>{error && <div className="mt-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_340px]"><section className="overflow-hidden rounded-lg border border-[#dfe6e6] bg-white"><div className="flex items-center justify-between border-b border-[#edf0f0] px-5 py-4"><div><h2 className="text-sm font-semibold">资料内容</h2><p className="mt-1 text-xs text-[#819092]">支持 PPTX、PDF、DOCX、Markdown、TXT 和智云课堂字幕</p></div><span className="text-xs text-[#819092]">{detail.resources.length} 项</span></div>{detail.resources.length ? <div className="divide-y divide-[#edf0f0]">{detail.resources.map((resource) => { const Icon = iconFor(resource.kind); const revision = resource.current_revision; return <div key={resource.resource_id} className="flex items-center gap-3 px-5 py-4"><span className="grid size-9 place-items-center rounded-md bg-[#eef4f4] text-[#147d86]"><Icon size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{resource.title}</p><p className="mt-1 text-[11px] text-[#819092]">{resource.source_type === 'zhiyun' ? `${resource.kind === 'courseware' ? '智云课件页' : '智云字幕'} · 第 ${String(revision?.metadata.lecture_index ?? '-')} 讲` : revision?.filename} · {formatSize(revision?.size_bytes)}</p></div><span className={revision?.parse_status === 'ready' ? 'text-[#27774a]' : 'text-red-600'}>{revision?.parse_status === 'ready' ? <Check size={15} /> : revision?.parse_error || '解析失败'}</span>{revision?.parse_status === 'ready' && <Button variant="ghost" size="icon-sm" title="预览资料" onClick={() => void showPreview(resource)}><Eye size={15} /></Button>}</div>})}</div> : <div className="py-16 text-center text-sm text-[#718183]">上传文件或导入智云课程开始建立资料集</div>}</section>
      <aside className="space-y-5"><div className="rounded-lg border border-[#b8dadb] bg-[#f2f9f9] p-5"><h2 className="text-sm font-semibold">创建一次生成</h2><p className="mt-2 text-xs leading-5 text-[#657678]">下一步选择这次使用的具体资料，创建不可变输入快照，再配置课程教辅工作流。</p><Button disabled={!ready} onClick={() => navigate(`/datasets/${datasetId}/configure`)} className="mt-5 w-full bg-[#147d86] text-white hover:bg-[#116a72]">选择资料并配置</Button></div><div className="rounded-lg border border-[#dfe6e6] bg-white p-5"><h2 className="text-sm font-semibold">历史输入快照</h2>{detail.snapshots.length ? <div className="mt-3 space-y-3">{detail.snapshots.slice(0,5).map((snapshot) => <div key={snapshot.snapshot_id} className="rounded-md bg-[#f7f9f9] p-3"><p className="text-xs font-medium">{snapshot.label || '未命名快照'}</p><p className="mt-1 text-[10px] text-[#819092]">{snapshot.resource_count} 项资料 · {snapshot.sha256.slice(0,8)}</p></div>)}</div> : <p className="mt-3 text-xs text-[#819092]">尚未创建快照</p>}</div></aside></div>
    {showImport && <ZhiyunImportDialog datasetId={datasetId} onClose={() => setShowImport(false)} onImported={() => { void load() }} />}
    {preview && <div className="fixed inset-0 z-40 flex justify-end bg-black/25" onClick={() => setPreview(null)}><div className="h-full w-[520px] overflow-auto bg-white p-7 shadow-xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-base font-semibold">{preview.title}</h2><Button variant="ghost" onClick={() => setPreview(null)}>关闭</Button></div><pre className="mt-6 whitespace-pre-wrap font-sans text-sm leading-7 text-[#425456]">{preview.text || '没有可预览文本'}</pre></div></div>}
  </div>
}
